# Generated by Django 4.2.25 on 2025-12-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventplanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Idea',
        ),
    ]
